// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SNPHWE2
double SNPHWE2(int32_t obs_hets, int32_t obs_hom1, int32_t obs_hom2, uint32_t midp);
RcppExport SEXP _HardyWeinberg_SNPHWE2(SEXP obs_hetsSEXP, SEXP obs_hom1SEXP, SEXP obs_hom2SEXP, SEXP midpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int32_t >::type obs_hets(obs_hetsSEXP);
    Rcpp::traits::input_parameter< int32_t >::type obs_hom1(obs_hom1SEXP);
    Rcpp::traits::input_parameter< int32_t >::type obs_hom2(obs_hom2SEXP);
    Rcpp::traits::input_parameter< uint32_t >::type midp(midpSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPHWE2(obs_hets, obs_hom1, obs_hom2, midp));
    return rcpp_result_gen;
END_RCPP
}
// SNPHWEX
double SNPHWEX(int32_t female_hets, int32_t female_hom1, int32_t female_hom2, int32_t male1, int32_t male2, uint32_t midp);
RcppExport SEXP _HardyWeinberg_SNPHWEX(SEXP female_hetsSEXP, SEXP female_hom1SEXP, SEXP female_hom2SEXP, SEXP male1SEXP, SEXP male2SEXP, SEXP midpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int32_t >::type female_hets(female_hetsSEXP);
    Rcpp::traits::input_parameter< int32_t >::type female_hom1(female_hom1SEXP);
    Rcpp::traits::input_parameter< int32_t >::type female_hom2(female_hom2SEXP);
    Rcpp::traits::input_parameter< int32_t >::type male1(male1SEXP);
    Rcpp::traits::input_parameter< int32_t >::type male2(male2SEXP);
    Rcpp::traits::input_parameter< uint32_t >::type midp(midpSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPHWEX(female_hets, female_hom1, female_hom2, male1, male2, midp));
    return rcpp_result_gen;
END_RCPP
}
// support
NumericMatrix support();
RcppExport SEXP _HardyWeinberg_support() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(support());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HardyWeinberg_SNPHWE2", (DL_FUNC) &_HardyWeinberg_SNPHWE2, 4},
    {"_HardyWeinberg_SNPHWEX", (DL_FUNC) &_HardyWeinberg_SNPHWEX, 6},
    {"_HardyWeinberg_support", (DL_FUNC) &_HardyWeinberg_support, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_HardyWeinberg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
